### ISSUE TITLE
Registration - Users should be able to register in the system (organizers or customers) and only registered users are allowed to buy and sell event tickets

### ISSUE THREAD

**Issue by KevinKim99** [KevinKim99/Ticket-Tech#20]

**Comment by KenichiroAnderson** [comment]
![Screenshot 2024-02-29 104055](https://github.com/KevinKim99/Ticket-Tech/assets/77311753/ec47d534-38d1-414d-8804-456171c3b88e)
Sign up/register made this has password validation that ensures that the users enter a valid password users must fill out all fields or the form will not submit. email also has validation, must have the'@' symbol and a .com or .'xxxxx' of some type: 
![Screenshot 2024-02-29 104254](https://github.com/KevinKim99/Ticket-Tech/assets/77311753/b184de78-6ad0-4e12-a4de-c72fae386b78)
Password Mismatch errors handling as the passowrds must match, the passwords peramteters are not 100% yet: 
![Screenshot 2024-02-29 104323](https://github.com/KevinKim99/Ticket-Tech/assets/77311753/823ddb79-8788-4332-82d9-1648628acf55)

**Comment by KevinKim99** [comment]
Email and password validation looks well implemented

**Comment by KenichiroAnderson** [comment]
done as of April 04, 2024
