### ISSUE TITLE
Login - Registered users should be able to log in to the system using their credentials

### ISSUE THREAD

**Issue by KevinKim99** [KevinKim99/Ticket-Tech#21]

**Comment by KenichiroAnderson** [comment]
![Screenshot 2024-02-29 104019](https://github.com/KevinKim99/Ticket-Tech/assets/77311753/e4a5a43f-614b-41c7-b5a0-0f901ad9ec95)
Login page made it works client side validation.

**Comment by KenichiroAnderson** [comment]
done
